cognizance-amrita/hacktoberfest

README.md

chore : Updated README.md

---

python/Time Delta.py

Create Time Delta.py

---

c++/Operator Overloading.cpp

Finished Operator Overloading

---

java/Solution.java

priority_queue.java

---

C/A_very_big_sum.c

sorry for raising pr done using c language 
Issue : #30

A_very_big_sum.c

---

python/Staircase_#38.py

Staircase_#38.py

---

java/staircase.java

Solution to staircase problem using java 
Issue : #38

staircase problem

---

python/A_Very_Big_Sum_#30.py

A_Very_Big_Sum_#30.py

---

python/Left_Rotation_#40.py

Left_Rotation_#40.py

---

java/Graph.java

The solution uses a primitive implementation of the graph and uses List Library for validation. Closes #15

Created Component Connection Problem solution

---

c++/Grading_Students_#34.cpp

Grading_Students_#34.cpp

---

C/Staircase.c

Solution to staircase problem in C
Issue: #38

Staircase Problem #38

---

c++/ClimbingStairs_DP.cpp

Shown the implementation of climbing stairs porblem by using both top down and bottom up dynamic programming algorithms.
Issue : #38

Added Climbing Stairs problem (Dynamic Programming)

---

java/leftrotation.java

LeftRotation in java

---

C/left_rotation.c

solution of left rotation in c

left rotation

---

C/Grading_Students.c

Grading_Students #34

---

c++/Left Rotation.cpp

Finished Left Rotation in C++

---

python/Finding_the_percentage_#58.py

Finding_the_percentage_#58.py

---

python/Lists_#57.py

Lists_#57.py

---

python/Day_of_the_programmer_#59.py

Day_of_the_programmer_#59.py

---

c++/Compare-The-Triplets.cpp

@ndrohith09 can you please merge my pr for issue #66

Solved #66 in C++

---

java/Birthday_Cake_Candles.java

Birthday Cake Candles #67

---

python/Time Conversion.py

I have changed the file format from ipynb to py.... Please accept my pr.

Create Time Conversion.py

---

python/Birthday_Cake_Candles #67.py

To solve this issue we can get the maximum height from the list of candles and then count how many times that maximum height occurs in the list, which was possible using a for loop.
Issue : #67

Create Birthday_Cake_Candles #67.py

---

c++/Migratory_birds_#69.cpp

Migratory_birds_#69.cpp

---

c++/Bill_division_#70.cpp

Bill_division_#70.cpp

---

c++/Time_Conversion_#68.cpp

Time_Conversion_#68.cpp

---

c++/Birthday_cake_candles_#67.cpp

Birthday_cake_candles_#67.cpp

---

java/Day_of_the_programmer.java

Day_of_the_programmer_#59.java

---

C/reverse_doubly_LL.c

Add code of reverse doubly linked list

---

python/time_delta.py

Time delta solution in python without any libraries
Variable description :-
n - No.of test cases
t1 ,t2 - Stores the data about Time 1 & 2
Calc function(used to calc delta in t1,t2 . Returns delta in seconds) :- d - difference in days along with months
y - differencce in years
hourd - delta in hours
mind - minutes differencce
secd - Difference in seconds
f_sec - final delta of both time's in seconds.
days_in_month function :- Returns days difference if both the months are different month_int function :- Returns Month number based on its string (used in days_in_month func)
Based on  #5

Solve Time_delta  in python

---

C/Cats_And_Mouse.c
C/Compare_The_Triplets.c

Cats_And_A_Mouse

---

java/Bill_div.java
python/Bill_div.py

Issue #70 : Resolve Bill divison issue in java & python

---

c++/Finding_The_Percentage_#58.c++

New and Updated code for Problem Finding the Percentage #58

#58 Updated and Working

---

C/Birthday_Cake_candles.c

resolves #67 Birthday_Cake_candles question in the leftover lang C.

Issue #67 : Solve in C

---

java/Cats_And_Mouse.java

resolves #101 Cats_And_Mouse issue in java

Issue #101 : Resolved in java

---

java/Finding_the_percentage.java

resolves #58 Finding_the_percentage question in java.

Issue #58 : Solved in java

---

java/Migratory_birds.java

resolves #69 Migratory_birds in java.
Variable Description :-
len - lenght of the array
birds[] - Array of birds aighting
In function migratory birds(returns the lowest type id of the most frequently sighted birds) :-
hc - Stores the  count of highest sights
sb - stores the id of the highest sighting bird
count - Used to store the count of sights of a bird

Issue #69 : Solve in java

---

C/Time_Conversion.c

Finished Time Conversion in C

---

java/Delete_a_node.java
python/Delete_a_node.py

resolves #84 Delete_a_node in python & java

Issue #84 : Resolve in python

---

c++/cat_mouse.cpp

 cat_mouse.cpp

---

java/bill_divisi

solved bill_division in java

---

c++/leftrotation.cpp

 # 40 leftrotation.cpp

---

C/stair_case.c

solved this issue in c programming language
Based on #38

# 38 issue : stair_case.c

---

c++/Day_Of_Programmer.cpp

Finished Day of programmer in C++

---

C/Runner_up_score.c
c++/A_very_big_sum_#30.c++

Code to the problem A very big sum #30 and Runner up Score #56 in c++ and c respectively

Solutions to #30 and #56

---

c++/Designer_PDF_Viewer_#124.c++

Code in c++ for the issue Designer PDF Viewer #124

Issue #124

---

C#/Birthday Cake Candles.cs
C#/Migratory Birds.cs

Issue #59 : Day of the programmer

---

C#/Birthday Cake Candles.cs
C#/Day of the prgrammer.cs
C#/Migratory Birds.cs

Issue #69 : Migratory Birds

---

java/pdfViewer.java

based on #124 pdfViewer in Java

Issue #124 : Contribute in Java

---

C#/A_very_big_sum.cs
C#/Cats_and_a_Mouse.cs

Cat And A Mouse

---

CastleOnTheGrid.java

Java solution for Castle on the Grid problem

Added code for Castle on the Grid problem

---

Ruby/Time_Conversion_#68.rb

Time Conversion #68

---

C#/Array_Reversal_#7.cs

@ndrohith09 Added array_reversal program issue#7 in C# language program. Kindly review it as soon as possible and merge it with main.

Added array_reversal in c#

---

c++/Find_Runnerup_Score.cpp
python/Compare_the_triplets.py

@ndrohith09 Added Compare_the_triplets in Python Folder. Kindly review it as soon as possible and merge it with main.

Added Compare_the_triplets in Python

---

c++/stair.cpp

Solved #38 in cpp
